<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Features\QuizAttempts\CreateQuizAttempt\**" />
	  <Compile Remove="Features\QuizAttempts\DeleteQuizAttempt\**" />
	  <Compile Remove="Features\QuizAttempts\UpdateQuizAttempt\**" />
	  <Compile Remove="Features\QuizQuestions\GetAllQuizQuestions\**" />
	  <EmbeddedResource Remove="Features\QuizAttempts\CreateQuizAttempt\**" />
	  <EmbeddedResource Remove="Features\QuizAttempts\DeleteQuizAttempt\**" />
	  <EmbeddedResource Remove="Features\QuizAttempts\UpdateQuizAttempt\**" />
	  <EmbeddedResource Remove="Features\QuizQuestions\GetAllQuizQuestions\**" />
	  <None Remove="Features\QuizAttempts\CreateQuizAttempt\**" />
	  <None Remove="Features\QuizAttempts\DeleteQuizAttempt\**" />
	  <None Remove="Features\QuizAttempts\UpdateQuizAttempt\**" />
	  <None Remove="Features\QuizQuestions\GetAllQuizQuestions\**" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SSS.Domain\SSS.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MediatR" Version="13.0.0" />
		<PackageReference Include="AutoMapper" Version="15.0.1" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Features\QuizAttempts\CreateQuizAttempt\" />
	  <Folder Include="Features\QuizAttempts\DeleteQuizAttempt\" />
	  <Folder Include="Features\QuizAttempts\UpdateQuizAttempt\" />
	  <Folder Include="Features\QuizQuestions\GetAllQuizQuestions\" />
	</ItemGroup>

</Project>
