<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5cf0623e-fa39-415b-b1c3-36d4151010d6</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\SSS.Infrastructure\SSS.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Endpoints\Content\LearningSubject\" />
	  <Folder Include="Endpoints\Content\Roadmap\GetRoadMapByManager\" />
	</ItemGroup>

</Project>
