using MediatR;
using Microsoft.EntityFrameworkCore;
using SSS.Application.Abstractions.Persistence.Mongo.Interfaces;
using SSS.Application.Abstractions.Persistence.Sql;
using SSS.Application.Common.Exceptions;
using SSS.Application.Features.StudySessions.Common;
using SSS.Domain.Entities.Tracking;
using SSS.Domain.Enums;
using System.Text.Json;

namespace SSS.Application.Features.StudySessions.LogStudyEvent
{
    public class LogStudyEventHandler(IAppDbContext context, IStudyEventRepository studyEventRepository)
        : IRequestHandler<LogStudyEventCommand, LogStudyEventResult>
    {
        public async Task<LogStudyEventResult> Handle(LogStudyEventCommand req, CancellationToken ct)
        {
            // Validate session exists and belongs to user (SQL)
            var sessionExists = await context.StudySessions
                .AnyAsync(s => s.Id == req.SessionId && s.UserId == req.UserId, ct);

            if (!sessionExists)
                throw new NotFoundException($"Session {req.SessionId} not found");

            // Parse event type — dùng StudyEventType: View, Click, Start, Submit, Complete
            if (!Enum.TryParse<StudyEventType>(req.EventType, true, out var eventType))
                throw new ConflictException(
                    $"Invalid event type: '{req.EventType}'. " +
                    $"Valid values: {string.Join(", ", Enum.GetNames<StudyEventType>())}");

            // Parse optional fields với giá trị mặc định
            var eventCategory = Enum.TryParse<StudyEventCategory>(req.EventCategory, true, out var cat)
                ? cat
                : StudyEventCategory.Learning;

            var contentMode = Enum.TryParse<ContentMode>(req.ContentMode, true, out var mode)
                ? mode
                : ContentMode.Text;

            // Convert metadata from JsonElement to native .NET types for MongoDB serialization
            var payload = ConvertMetadata(req.Metadata);

            var studyEvent = new StudyEvent
            {
                SessionId = req.SessionId,
                EventType = eventType,
                EventCategory = eventCategory,
                ContentMode = contentMode,
                EventTimestamp = DateTime.UtcNow,
                Payload = payload,
                DeviceInfo = new Dictionary<string, object>()
            };

            // Save to MongoDB (Id is auto-generated by MongoDB)
            await studyEventRepository.AddAsync(studyEvent);

            return new LogStudyEventResult
            {
                Success = true,
                Data = new StudyEventDto
                {
                    Id = studyEvent.Id,
                    SessionId = req.SessionId,
                    EventType = req.EventType,
                    TaskId = req.TaskId,
                    Timestamp = studyEvent.EventTimestamp
                }
            };
        }

        /// <summary>
        /// Convert Dictionary values from JsonElement (System.Text.Json) to native .NET types
        /// so MongoDB BsonSerializer can handle them.
        /// </summary>
        private static Dictionary<string, object> ConvertMetadata(Dictionary<string, object>? metadata)
        {
            if (metadata == null || metadata.Count == 0)
                return new Dictionary<string, object>();

            var result = new Dictionary<string, object>();
            foreach (var kvp in metadata)
            {
                result[kvp.Key] = ConvertValue(kvp.Value);
            }
            return result;
        }

        private static object ConvertValue(object value)
        {
            if (value is JsonElement element)
            {
                return element.ValueKind switch
                {
                    JsonValueKind.String => element.GetString()!,
                    JsonValueKind.Number => element.TryGetInt64(out var l) ? l : element.GetDouble(),
                    JsonValueKind.True => true,
                    JsonValueKind.False => false,
                    JsonValueKind.Null => null!,
                    JsonValueKind.Array => element.EnumerateArray().Select(e => ConvertValue(e)).ToList(),
                    JsonValueKind.Object => element.EnumerateObject()
                        .ToDictionary(p => p.Name, p => ConvertValue(p.Value)),
                    _ => value.ToString()!
                };
            }
            return value;
        }
    }
}
